name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run CDK infrastructure tests
      run: npm test
      
    - name: Install website dependencies
      run: |
        cd website
        npm ci
    
    - name: Run website unit tests
      run: |
        cd website
        npm test

  build-and-deploy:
    name: Build and Deploy
    needs: test  # This ensures deployment only happens if tests pass
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build React application
      run: |
        cd website
        npm ci
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: CDK Bootstrap
      run: npx cdk bootstrap
      
    - name: CDK Deploy
      run: npx cdk deploy --require-approval never
    
    - name: Get website URL
      id: get-url
      run: |
        URL=$(aws cloudformation describe-stacks --stack-name CdkS3WebsiteStack --query "Stacks[0].Outputs[?OutputKey=='WebsiteURL'].OutputValue" --output text)
        echo "WEBSITE_URL=$URL" >> $GITHUB_ENV
        echo "Website deployed successfully! Visit: $URL"
